steps:
  # Step 1: Install dependencies (using a Docker container with Python)
  - name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'flask-api-service'  # Name of your Cloud Run service
      - '--image=gcr.io/$PROJECT_ID/$REPO_NAME'  # Set your image name
      - '--platform=managed'
      - '--region=us-central1'  # Change as per your region
      - '--allow-unauthenticated'  # For public access, remove if you need authentication

timeout: '1200s'  # Optional: Timeout for the build process
