steps:
  # Step 1: Build Docker image with both SHA and "latest" tags
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    dir: '.'
    args:
      [
        'build',
        '-t', 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:$SHORT_SHA',
        '-t', 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:latest',
        '.'
      ]

  # Step 2: Push both tags
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image - SHA'
    args:
      [
        'push',
        'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:$SHORT_SHA'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image - Latest'
    args:
      [
        'push',
        'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:latest'
      ]

  # Step 3: Deploy to Cloud Run using SHA-tagged image and Gmail secret
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'phishing-backend',
        '--image', 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:$SHORT_SHA',
        '--region', 'us-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--timeout', '900s',
        '--memory', '2Gi',
        '--cpu', '2',
        '--max-instances', '5',
        '--service-account', 'model-accessor@phishing-detection-450717.iam.gserviceaccount.com',
        '--set-secrets',
        'GMAIL_CREDENTIALS=gmail-oauth-credentials:latest'
      ]

images:
  - 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:$SHORT_SHA'
  - 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
  dynamicSubstitutions: true
  substitutionOption: ALLOW_LOOSE

timeout: 1200s
