steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend',
      '.'
    ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend'
    ]

  # Step 3: Deploy the container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'phishing-backend',
        '--image', 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend',
        '--region', 'us-west1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--timeout', '900s',  # ⏳ Extended timeout (optional but useful if model loading is slow)
        '--memory', '1Gi'     # 📦 Increase memory if needed
      ]

images:
  - 'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishing-backend'

options:
  logging: CLOUD_LOGGING_ONLY
