steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/flask-api-service',
        '.'
      ]

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/flask-api-service'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud',
        'run',
        'deploy',
        'flask-api-service',
        '--image=gcr.io/$PROJECT_ID/flask-api-service',
        '--platform=managed',
        '--region=us-central1',
        '--allow-unauthenticated'
      ]

# Optional: Log configuration and timeout
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
timeout: '1200s'
