steps:
  # Step 1: Build the Docker image (no cache to avoid stale requirements issues)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--no-cache',
        '-t',
        'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishimg',
        '.'
      ]

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishimg'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'flask-api-service',
        '--image=us-west1-docker.pkg.dev/phishing-detection-450717/phishing-detection-backend/phishimg',
        '--platform=managed',
        '--region=us-west1',
        '--allow-unauthenticated'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  machineType: E2_HIGHCPU_8  # Optional: faster build
  env:
    - DOCKER_BUILDKIT=1

timeout: '1200s'
