steps:
  # Step 1: Build the Docker image from current directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/phishing-detection-450717/flask-api-service',
        '.'
      ]

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/phishing-detection-450717/flask-api-service'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'flask-api-service',
        '--image=gcr.io/phishing-detection-450717/flask-api-service',
        '--platform=managed',
        '--region=us-central1',
        '--allow-unauthenticated'
      ]

# Optional settings
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
timeout: '1200s'
